### ISSUE TITLE
Annotation import process is confusing.

### ISSUE THREAD

**Issue by arkob** [tecoholic/ner-annotator#103]
Can you add the feature to revise annotations? I have .json file with annotations done by your tool. I want to revise them and check. No option to open .json file and revise it.

**Comment by alvi-khan** [comment]
![image](https://github.com/tecoholic/ner-annotator/assets/55395950/07dca972-fc20-4373-98e6-4de8ec65d62c)

Hello! It's possible to open an existing annotation file by first opening the base text file and then importing the .json file using the menu option.

**Comment by alvi-khan** [comment]
I can see how the import process can be confusing. I've had more questions about this too. I'm keeping this issue open until this is improved.

**Comment by GiovanniNova** [comment]
We should be able to import straight from the .json file since it already contains the text. Why is the .txt file necessary?

**Comment by alvi-khan** [comment]
> We should be able to import straight from the .json file since it already contains the text. Why is the .txt file necessary?

The .txt and .json files aren't exactly the same unfortunately. For example, if you skip a sentence then the .json file has a NULL value in the place of the sentence.

I also disagree that we should import the text from the .json file. In my own experience, a major use case for importing the .json file is to review the annotations done by someone else. You would then be trusting that the .json file really did include all of the sentences from the original text and that the original text was unmodified.

**Comment by GiovanniNova** [comment]
It would be a nice option thats all, a warning could be displayed when importing the .json without the .txt file.
