### ISSUE TITLE
cannot start it

### ISSUE THREAD

**Issue by kulig1985** [tecoholic/ner-annotator#108]
i cloned the repository, and try to start with yarn serve command got this:

```
qg@optimus:~/dockers/llm/annotate/ner-annotator$ yarn serve
ERROR: [Errno 2] No such file or directory: 'serve'
```
how can i start the web application?

**Comment by tecoholic** [comment]
@kulig1985 Kindly see https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install
