### ISSUE TITLE
Clear pre-loaded annotations for a particular data point.

### ISSUE THREAD

**Issue by Akhilesh64** [tecoholic/ner-annotator#115]
Hi @tecoholic @alvi-khan
I was wondering if you could add a feature for clearing pre-loaded annotations for a particular data point. Like you could give a button/shortcut to clear all annotations for the data point on screen. I am tring to auto-annotate a dataset with a pretrained model and then load those annotations for corrections. It becomes cumbersome to clear the annotations which are very wrong and this could be a useful feature.

**Comment by alvi-khan** [comment]
Hello @Akhilesh64! We already have this feature. The 'Reset' button on the bottom left does exactly this.
![image](https://github.com/tecoholic/ner-annotator/assets/55395950/a2a6855f-7e3d-45d4-b52c-a998fa4786f5)
