### ISSUE TITLE
Web version not available for now. Do you plan support it? Or recommend look for something new?

### ISSUE THREAD

**Issue by EllaLytvyn** [tecoholic/ner-annotator#123]
Something unexpected happened while accessing this website. It looks like it doesn't have an active [domain connection](https://wordpress.com/support/domains/connect-existing-domain/) upgrade to link the requested domain name to the WordPress.com site.

If this is your domain name and it has recently stopped working, it's possible that your plan or domain may have expired. Please [log in](https://wordpress.com/wp-login.php) to your WordPress.com account and review the status of your plan and domain.

**Comment by tecoholic** [comment]
@EllaLytvyn I just checked the link from the project page, it just redirects to my personal domain, but the tool still loads.

Try https://arunmozhi.in/ner-annotator/ if it's not redirecting you to the app.

**Comment by EllaLytvyn** [comment]
Today it is works. Thanks!)
