### ISSUE TITLE
Storing tags in NER Annotator

### ISSUE THREAD

**Issue by nitesh140892** [tecoholic/ner-annotator#14]
there has to be a config file or functionality of storing tags, such that we can use them between sessions.

**Comment by tecoholic** [comment]
There is a couple of ways to do this:

- *config file* - This will allow us to load the tags during the app build time and have them available during the tagging. But browsers cannot directly write to the disk. So it has to be downloaded and saved by the user.
- *local storage* - A better option IMO is to store config in the `localstorage` of the browser. This will allow for better tag menagement, we can group them into projects and load the set required.

**Comment by nitesh140892** [comment]
I also agree that local storage is a better option, given that session is maintained throughout different files worked with annotations.

Also, if if we can group them into projects, as you said, and load them later, it is even better.
