### ISSUE TITLE
Error: timeout of 3000ms exceeded

### ISSUE THREAD

**Issue by seanbenhur** [tecoholic/ner-annotator#18]
Whenever I try to upload my training data, i get this error, How to prevent this and start annotating!?

**Comment by tecoholic** [comment]
@seanbenhur Make sure you have the Python `server.py` running in a separate terminal. This Error is usually when you forget to start the background Python Server.

**Comment by seanbenhur** [comment]
Sorry, Actually  I was running the server but not on the virtual environment, Thanks for the response!
