### ISSUE TITLE
Error: timeout of 3000ms exceeded

### ISSUE THREAD

**Issue by taghouti-ghofrane** [tecoholic/ner-annotator#2]

**Comment by taghouti-ghofrane** [comment]
i run the code and that was my error can any explain to me what can i do

**Comment by tecoholic** [comment]
Are you running two terminals, one for the backend and one for the web ui?

**Comment by taghouti-ghofrane** [comment]
i am running  2 terminals :
![image](https://user-images.githubusercontent.com/45640918/100612481-55188e80-3313-11eb-8c6f-8d68dda637ec.png)

**Comment by tecoholic** [comment]
Make sure you are running the backend server in the first terminal.

```
pip install -r requirements.txt   # installs requirements

python annotator/server.py 
```

**Comment by taghouti-ghofrane** [comment]
it works Thanks 👍
