### ISSUE TITLE
Annotation tool for relation extraction

### ISSUE THREAD

**Issue by MarurSrikanta** [tecoholic/ner-annotator#20]
Thanks for this amazing tool, it works very well.
Would you know of a data annotation tool for relation extraction? I tried searching the web but couldnt find a tool that can accomplish relation extraction. UBAI tool is paid service and doesnt work well for custom model. It would be great if you can recommend  an unpaid tool for relation extraction.

**Comment by tecoholic** [comment]
@MarurSrikanta I don't know of any such tools.
