### ISSUE TITLE
Running tool on remote server for collaborative tagging activity

### ISSUE THREAD

**Issue by parth-gadoya** [tecoholic/ner-annotator#22]
I was wondering if I can start "ner-annotator" tool on remote server and multiple users can simultaneously do tagging on different corpus.

So, user can select corpus from their local machine, but server will not be running on local machine.

Anyone, have tried doing this? Let me know if anyone has ideas to achieve this.

Thanks.

**Comment by tecoholic** [comment]
@parth-gadoya Hi, it would require the server knowing about the tagging process. Currently the only thing the server does for  us is tokenize the text. Everything else happens on the client's browser. So it won't be possible at the moment. I would suggest splitting the corpus into multiple files and sharing it with the collaborators as a workaround.
