### ISSUE TITLE
Docker install fails to build server.Dockerfile

### ISSUE THREAD

**Issue by NTBTI** [tecoholic/ner-annotator#24]
It appears the python slim package does not have GCC which is needed

#8 6.315     gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/include/python3.10 -c regex_3/_regex.c -o build/temp.linux-x86_64-3.10/regex_3/_regex.o
#8 6.315     error: command 'gcc' failed: No such file or directory
#8 6.315     ----------------------------------------
#8 6.316 ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7i04flgx/regex_ac4e0ddea9bf47599020bcf405efdfaa/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7i04flgx/regex_ac4e0ddea9bf47599020bcf405efdfaa/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-2vi5dim1/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.10/regex Check the logs for full command output.
------
executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements.txt]: exit code: 1

**Comment by plasmon360** [comment]
```
RUN apt-get update \
&& apt-get install gcc -y \
&& apt-get clean
```

solves the problem.

**Comment by tecoholic** [comment]
Docker and local setup is no longer required.
