### ISSUE TITLE
Doubt about POS and DEP!!

### ISSUE THREAD

**Issue by JessitaMS** [tecoholic/ner-annotator#32]
Hi!

I'm newly in this NLP world, so I have a doubt about the POS and Dependencies. When your training your blank model of spacy for NER, you omited components in the pipeline as: tagger, and passer. So my doubt how would add in the training_data.spacy before train the model. I'm asking you this, because your video is the most detailed that I've been seen of this theme and it's Excellent!!. Can you help me with this issue that I have.

Regards,

**Comment by tecoholic** [comment]
@JessitaMS I would suggest posting the question in [spaCy Discussions](https://github.com/explosion/spaCy/discussions). This repository only is focused on NER Tagging UI and the model building code is only an example to show the workflow. I hope this helps.
