### ISSUE TITLE
How to fix common Ner Tag for all the different text file.

### ISSUE THREAD

**Issue by kunalchoudhary33** [tecoholic/ner-annotator#33]
Hello Team, 

I appreciate for building this beautiful tool for annotating the text file for NER. 

I want to annotate 10000 different text file with fixed number of common Ner Tag for all the text files. I have to every time add the same Ner Tag reputedly for all text file. 

Since I am using the application in my local using localhost. Can you please help me to make the code change in my local to fix the common tag for all the text file. Since I do not have much experience in front end applications, any help would really be appreciated.

I would really appreciate if you could help me to fix the tags.

**Comment by tecoholic** [comment]
@kunalchoudhary33 There is going to some feature updates in the upcoming release. I will try to include importing and exporting of tags in them. Thanks for bringing up the usecase.
