### ISSUE TITLE
Can we install tool on windows?

### ISSUE THREAD

**Issue by sainathpawar** [tecoholic/ner-annotator#37]
How to install tools on windows operating system. Please guide

**Comment by tecoholic** [comment]
@sainathpawar There is no way to install it in windows currently. Kindly use the web version from Windows. The functionality is the same. https://tecoholic.github.io/ner-annotator/

**Comment by tecoholic** [comment]
@sainathpawar You can now install it in windows using this installer https://github.com/tecoholic/ner-annotator/releases/download/v1.0.2/NER.Annotator_1.0.2_x64.msi

**Comment by sainathpawar** [comment]
Thanks @tecoholic its really wonderful. Appreciate for quickly turnaround on solution for windows user. I was getting lot off issue while training data that was annotated by doccano. but you save me. I am able to train the model on data annotated by your tools without any issue. Thank you so much. It would be great
-  if you can add option to import new file once annotation is done for one file.

**Comment by tecoholic** [comment]
@sainathpawar It's always great to hear such positive feedback. I understand what you are suggesting. I will add it my issue list. Thanks
