### ISSUE TITLE
Capability to annotate portion of a word

### ISSUE THREAD

**Issue by rounakdatta** [tecoholic/ner-annotator#42]
In my project, given the text is not properly cleansed, I'd often want to annotate a portion of a word. Can we introduce support for this in the tool?

For example, today LabelStudio supports this,
<img width="479" alt="image" src="https://user-images.githubusercontent.com/20105014/158978098-924ee2d8-c9b9-44b8-a0bc-9c3609e3b06b.png">

Also, as a clarification, even if we introduce the support in this tool, does spaCy support partial words?

**Comment by tecoholic** [comment]
@rounakdatta I don't think this would be implemented. One of the UX choices made early in the software was to allow quick selection of tokens without worrying about clicking the exact starts and ends. So even if you select like 1 character in the middle of the word, the entire word gets tagged.

This suggestion would make it break that functionality, which probably won't be done. I suggest cleaning the text beforehand.
