### ISSUE TITLE
Text Encoding

### ISSUE THREAD

**Issue by mathieugrasland** [tecoholic/ner-annotator#57]
The tool doesn't understand ANSI encoding or microsoft.
![image](https://user-images.githubusercontent.com/54704295/203608194-258ae5ce-891b-4a1b-a438-b38353009e1c.png)

Could we change encoding or find a way to detect it ?

Using the windows msi installer.

Thank you for your tool !

**Comment by tecoholic** [comment]
@mathieugrasland Could you try changing the Encoding of the text file in the "Save As" dialog and see if that helps? I don't spend much time on developing this anymore and I can't add encoding detection. Sorry.

**Comment by mathieugrasland** [comment]
Oh understood.
It won't work because there letters like éè.
Thanks for the tool by the way 👍
