### ISSUE TITLE
Very Cool Tools - Two Questions

### ISSUE THREAD

**Issue by GuoyiLi1991** [tecoholic/ner-annotator#6]
First, Thanks a lot for creating this tools!

It's really useful to my since I am recently using SpaCy as well! Two questions. 

1. While annotating a file, can we have a function of going back and re-annotate the previous sentences so that we could correct errors if any? Or after we completing, may we have a bottom to go back to the home page? (I could do it by reloading the web for now).
2. I don't know if it's a bug or not... when I annotated a sentence and assign a tag to the last word, the last word will disappear. Then I found if my tagging include the last word, the selected portion of the sentences will disappear. I am not sure what is happening. The file I uploaded to be annotated was a text file with sentences listed line by line, not sure if it matters.

One more thing, actually I am willing to contribute to you repo if you need so extra labor... Since I am Data scientist, I may only be able to do the Python part... but if you need, I am happy to...

Thanks,
Guoyi

**Comment by tecoholic** [comment]
@GuoyiLi1991 Thank you for taking the time to open this issue. Both of the issues could be possible and I would be happy to fix them. Can you open them as separate issues with steps to reproduce and preferably attach a test file as well? I can test and bug fix accordingly?
