### ISSUE TITLE
Issue about the code.

### ISSUE THREAD

**Issue by GuoyiLi1991** [tecoholic/ner-annotator#7]
Steps to reproduce:

1, Git clone the repo and build the source code.
2. Run python serve.py
3. yarn serve
4. open browser then go to http://localhost:8080/

a. Issue one: 
While annotating a file, can we have a function of going back and re-annotate the previous sentences so that we could correct errors if any? Or after we completing, may we have a bottom to go back to the home page? (I could do it by reloading the web for now).

For now, I don't see any options to go back and to the previous annotation. Only has reset, save and skip.
![image](https://user-images.githubusercontent.com/29215691/104965018-be2f9080-59ab-11eb-8b89-52799cdc87b3.png)

2. when I annotated a sentence and assign a tag to the last word, the last word will disappear. Then I found if my tagging include the last word, the selected portion of the sentences will disappear. I am not sure what is happening. The file I uploaded to be annotated was a text file with sentences listed line by line, not sure if it matters.

For example, as shown here, I defined a entity named "A" and I annotated the sentence "I am going to walmart". If I assign A to "going" it will be fine.
![image](https://user-images.githubusercontent.com/29215691/104965141-11a1de80-59ac-11eb-9ea2-c3455141bb91.png)

But if I assign A to "walmart", the word "walmart will disappear"...
![image](https://user-images.githubusercontent.com/29215691/104965193-2d0ce980-59ac-11eb-94fb-5da613079d4a.png)

Please let me know if you need any other details.

Thanks,
Guoyi

**Comment by tecoholic** [comment]
@GuoyiLi1991 Thank you for such a clear report. This will do.

**Comment by GuoyiLi1991** [comment]
@tecoholic No problem at all. Please let me know if you need any extra labor.

**Comment by ConMan05** [comment]
Is the issue resolved ??? I too have that issue ...

**Comment by tecoholic** [comment]
PR #11 is supposed to solve the test disappearance issue. Merged. Closing for now. Reopen if it occurs again.
